name: Design Documents Version Release Please

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout From Repo
        uses: actions/checkout@v4

      - name: Run Release Please
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: simple
          token: ${{ secrets.RELEASE_TOKEN }}
          changelog-path: changelog.md
          update-changelog: true 